import React,{ createContext, useState, useEffect } from 'react'
import { Routes, Route } from 'react-router-dom'
import Home from './pages/Home'
import Login from './pages/Login'
import Signup from './pages/Signup'
import RiderDashboard from './pages/RiderDashboard'
import DriverDashboard from './pages/DriverDashboard'
import Header from './components/Header'
import { AuthContext } from './context/AuthContext'
import useSocket from '../hooks/useSocket'
import api from '../api/api'           
import Map from '../components/Map'